---
- name: Check if golang exists
  stat: path=/usr/bin/go
  register: check_go_bin

- name: Download godeb
  get_url:
    url: "https://godeb.s3.amazonaws.com/godeb-amd64.tar.gz"
    dest: "/home/vagrant/godeb.tar.gz"
  when: check_go_bin.stat.exists == false

- name: unzip godeb
  unarchive: src=/home/vagrant/godeb.tar.gz dest=/home/vagrant copy=no
  when: check_go_bin.stat.exists == false

- name: install golang
  shell: "/home/vagrant/godeb install 1.6.1"
  when: check_go_bin.stat.exists == false

- name: remove godeb files
  file: path=/home/vagrant/{{ item }} state=absent
  with_items:
    - godeb
    - godeb.tar.gz
    - go_1.6.1-godeb1_amd64.deb
