---
- name: Remove chef and puppet
  apt: name={{ item }} state=absent purge=yes
  with_items:
    - chef
    - puppet
    - puppet-common

- name: Autoremove unused packages
  command: apt-get -y autoremove
  sudo: yes

- name: Clean apt
  command: apt-get clean
  sudo: yes
